env = Environment(CPPFLAGS=['-Wall','-g'])
env.ParseConfig('pkg-config --cflags --libs glib-2.0')
env.Append(CPPDEFINE=['HAVE_CONFIG_H'])

env.Append(CPPPATH = ['../lib',
                      '../charset'],
           LIBPATH = ['../lib/.libs'],
           LIBS=['fribidi'])

env.Program('test',
            ['test.c'],
            )

env.Program('test-character',
            ['test-character.c'],
            )

env.Program('bd16',
            ['bd16.c'])

env.Program('bd16-v1',
            ['bd16-v1.c',
             '../lib/fribidi-brackets.c'],
            CPPPATH=['../lib'] + env['CPPPATH'],
            CPPDEFINES=['HAVE_STRINGIZE=1',
                        'HAVE_STDINT_H=1'])

env.Program('test-bracketing',
            ['test-bracketing.c',
             '../lib/fribidi-brackets.c'],
            CPPPATH=['../lib'] + env['CPPPATH'],
            CPPDEFINES=['HAVE_STRINGIZE=1',
                        'HAVE_STDINT_H=1'])
